# Generated by Django 6.1.1 on 2026-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category__display_order', 'display_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='pricing_type',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
