# Generated by Django 6.1.1 on 2026-09-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_menuitem_options_remove_menuitem_pricing_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Order status histories'},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='final_price',
            new_name='final_amount',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_price',
            new_name='requested_amount',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='actual_weight',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='estimated_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='requested_weight',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Order Received'), ('preparing', 'Preparing Order'), ('braaiing', 'Braaiing'), ('ready', 'Ready for Collection'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('new', 'Order Received'), ('preparing', 'Preparing Order'), ('braaiing', 'Braaiing'), ('ready', 'Ready for Collection'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
