# Generated by Django 6.1.1 on 2026-09-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='pricing_type',
            field=models.CharField(choices=[('amount', 'Customer Enters Amount'), ('fixed', 'Fixed Price')], default='amount', max_length=20),
        ),
    ]
