# Generated by Django 6.1.1 on 2026-09-14 11:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
