# Generated by Django 6.1.1 on 2026-09-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_platform_fee_order_platform_fee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('online', 'Online'), ('counter', 'Over the Counter')], default='online', max_length=20),
        ),
    ]
