# Generated by Django 6.0.3 on 2026-09-21 08:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_shop_slug_alter_order_order_type_staffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='orders.shop')),
            ],
            options={
                'ordering': ['-year', '-month', 'shop__name'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'year', 'month'), name='unique_shop_monthly_subscription')],
            },
        ),
    ]
